import React from 'react';
import { IssueType, ReportStatus } from './types';

// SVG Icon Components - NEW SET OF 10 ICONS
export const MedicalEmergencyIcon: React.FC<{ className?: string }> = ({ className }) => (
    <svg xmlns="http://www.w3.org/2000/svg" className={className} fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
        <path strokeLinecap="round" strokeLinejoin="round" d="M12 12h.01M12 9v3m0 0v3m0-3h3m-3 0H9" />
    </svg>
);
export const SafetyConcernIcon: React.FC<{ className?: string }> = ({ className }) => (
    <svg xmlns="http://www.w3.org/2000/svg" className={className} fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
    </svg>
);
export const HarassmentIcon: React.FC<{ className?: string }> = ({ className }) => (
    <svg xmlns="http://www.w3.org/2000/svg" className={className} fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" d="M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636" />
    </svg>
);
export const TheftPropertyIcon: React.FC<{ className?: string }> = ({ className }) => (
    <svg xmlns="http://www.w3.org/2000/svg" className={className} fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 4.5h16.5M3.75 8.25h16.5M3.75 12h16.5m-16.5 3.75h16.5M5.25 4.5l7.5 7.5 7.5-7.5M5.25 19.5l7.5-7.5 7.5 7.5" />
    </svg>
);
export const LostPersonIcon: React.FC<{ className?: string }> = ({ className }) => (
    <svg xmlns="http://www.w3.org/2000/svg" className={className} fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" d="M15 19.128a9.38 9.38 0 002.625.372 9.337 9.337 0 004.121-.952 4.125 4.125 0 00-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.106A12.318 12.318 0 018.624 21c-2.331 0-4.512-.645-6.374-1.766l-.001-.109a6.375 6.375 0 0111.964-4.663c.11-.258.238-.5.39-.742M9.81 13.532A3.375 3.375 0 009 15.187m0 0A3.375 3.375 0 005.19 13.532m4.62 0a3.375 3.375 0 00-4.62 0m4.62 0a3.375 3.375 0 004.62 0m0 0A3.375 3.375 0 009 15.187" />
    </svg>
);
export const SanitationIssueIcon: React.FC<{ className?: string }> = ({ className }) => (
    <svg xmlns="http://www.w3.org/2000/svg" className={className} fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
    </svg>
);
export const FacilityMaintenanceIcon: React.FC<{ className?: string }> = ({ className }) => (
    <svg xmlns="http://www.w3.org/2000/svg" className={className} fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" d="M11.42 15.17L17.25 21A2.652 2.652 0 0021 17.25l-5.877-5.877M11.42 15.17l2.496-3.03c.317-.384.74-.664 1.208-.766M11.42 15.17l-4.636 2.541m-4.636-2.541l2.496-3.03c.317-.384.74-.664 1.208-.766M11.42 15.17L5.636 5.636m5.784 9.534l2.496-3.03m0 0l2.496-3.03m-2.496 3.03L8.132 8.132m6.356 7.038l2.496-3.03" />
    </svg>
);
export const FireHazardIcon: React.FC<{ className?: string }> = ({ className }) => (
    <svg xmlns="http://www.w3.org/2000/svg" className={className} fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" d="M15.362 5.214A8.252 8.252 0 0112 21 8.25 8.25 0 016.038 7.048 8.287 8.287 0 009 9.6a8.983 8.983 0 013.361-6.867 8.21 8.21 0 003 2.48z" />
        <path strokeLinecap="round" strokeLinejoin="round" d="M12 18a3.75 3.75 0 00.495-7.467 5.99 5.99 0 00-1.925 3.546 5.974 5.974 0 01-2.133-1A3.75 3.75 0 0012 18z" />
    </svg>
);
export const InfoQuestionIcon: React.FC<{ className?: string }> = ({ className }) => (
    <svg xmlns="http://www.w3.org/2000/svg" className={className} fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" d="M9.879 7.519c1.171-1.025 3.071-1.025 4.242 0 1.172 1.025 1.172 2.687 0 3.712-.203.179-.43.326-.67.442-.745.361-1.45.999-1.45 1.827v.75M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-9 5.25h.008v.008H12v-.008z" />
    </svg>
);
export const OtherIcon: React.FC<{ className?: string }> = ({ className }) => (
    <svg xmlns="http://www.w3.org/2000/svg" className={className} fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
);

export const SafetyIcon: React.FC<{ className?: string }> = ({ className }) => (
    <svg xmlns="http://www.w3.org/2000/svg" className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m0-10.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.75c0 5.592 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.57-.598-3.75h-.152c-3.196 0-6.1-1.249-8.25-3.286zm0 13.036h.008v.008H12v-.008z" />
    </svg>
);
export const LostAndFoundIcon: React.FC<{ className?: string }> = ({ className }) => (
    <svg xmlns="http://www.w3.org/2000/svg" className={className} fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
        <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 10.5h-6" />
    </svg>
);

export const TeamIcon: React.FC<{ className?: string }> = ({ className }) => (
    <svg xmlns="http://www.w3.org/2000/svg" className={className} viewBox="0 0 20 20" fill="currentColor"><path d="M9 6a3 3 0 11-6 0 3 3 0 016 0zm-1.5 5.25a2.25 2.25 0 00-4.5 0v.891a3.752 3.752 0 001.5 3.039v.659a1.5 1.5 0 003 0v-.659a3.752 3.752 0 001.5-3.039v-.891zM16.5 6a3 3 0 11-6 0 3 3 0 016 0zm-1.5 5.25a2.25 2.25 0 00-4.5 0v.891a3.752 3.752 0 001.5 3.039v.659a1.5 1.5 0 003 0v-.659a3.752 3.752 0 001.5-3.039v-.891z" /></svg>
);
export const SummaryIcon: React.FC<{ className?: string }> = ({ className }) => (
    <svg xmlns="http://www.w3.org/2000/svg" className={className} viewBox="0 0 20 20" fill="currentColor"><path fillRule="evenodd" d="M4.25 5.5a.75.75 0 00-.75.75v8.5c0 .414.336.75.75.75h11.5a.75.75 0 00.75-.75v-8.5a.75.75 0 00-.75-.75H4.25zM3.5 6.25a2.25 2.25 0 012.25-2.25h9.5a2.25 2.25 0 012.25 2.25v7.5a2.25 2.25 0 01-2.25 2.25h-9.5A2.25 2.25 0 013.5 13.75v-7.5z" clipRule="evenodd" /></svg>
);
export const AnonymousIcon: React.FC<{ className?: string }> = ({ className }) => (
    <svg xmlns="http://www.w3.org/2000/svg" className={className} viewBox="0 0 20 20" fill="currentColor"><path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-5.5-2.5a2.5 2.5 0 11-5 0 2.5 2.5 0 015 0zM10 12a5.99 5.99 0 00-4.793 2.39A6.483 6.483 0 0010 16.5a6.483 6.483 0 004.793-2.11A5.99 5.99 0 0010 12z" clipRule="evenodd" /></svg>
);

// Constant Details
export const ISSUE_TYPE_DETAILS: { [key in IssueType]: { icon: React.FC<{className?: string}>; key: string; accentColor: string } } = {
  [IssueType.MedicalEmergency]: { icon: MedicalEmergencyIcon, key: 'issue_MedicalEmergency', accentColor: 'border-red-500' },
  [IssueType.SafetyConcern]: { icon: SafetyConcernIcon, key: 'issue_SafetyConcern', accentColor: 'border-blue-500' },
  [IssueType.Harassment]: { icon: HarassmentIcon, key: 'issue_Harassment', accentColor: 'border-orange-500' },
  [IssueType.TheftProperty]: { icon: TheftPropertyIcon, key: 'issue_TheftProperty', accentColor: 'border-purple-500' },
  [IssueType.LostPerson]: { icon: LostPersonIcon, key: 'issue_LostPerson', accentColor: 'border-teal-500' },
  [IssueType.SanitationIssue]: { icon: SanitationIssueIcon, key: 'issue_SanitationIssue', accentColor: 'border-green-500' },
  [IssueType.FacilityMaintenance]: { icon: FacilityMaintenanceIcon, key: 'issue_FacilityMaintenance', accentColor: 'border-yellow-500' },
  [IssueType.FireHazard]: { icon: FireHazardIcon, key: 'issue_FireHazard', accentColor: 'border-red-700' },
  [IssueType.InfoQuestion]: { icon: InfoQuestionIcon, key: 'issue_InfoQuestion', accentColor: 'border-gray-500' },
  [IssueType.Other]: { icon: OtherIcon, key: 'issue_Other', accentColor: 'border-slate-500' },
};

export const STATUS_DETAILS: { [key in ReportStatus]: { key: string; color: string; textColor: string } } = {
  [ReportStatus.New]: { key: 'status_NEW', color: 'bg-blue-100 dark:bg-blue-900/50', textColor: 'text-blue-800 dark:text-blue-300' },
  [ReportStatus.InProgress]: { key: 'status_IN_PROGRESS', color: 'bg-yellow-100 dark:bg-yellow-900/50', textColor: 'text-yellow-800 dark:text-yellow-300' },
  [ReportStatus.Resolved]: { key: 'status_RESOLVED', color: 'bg-green-100 dark:bg-green-900/50', textColor: 'text-green-800 dark:text-green-300' },
};

export const PRIORITY_DETAILS: { [key in 'Low' | 'Medium' | 'High']: { key: string; color: string } } = {
  Low: { key: 'priority_Low', color: 'bg-green-500' },
  Medium: { key: 'priority_Medium', color: 'bg-yellow-500' },
  High: { key: 'priority_High', color: 'bg-red-500' },
};

export const EMERGENCY_SMS_NUMBER = '+917386262326';

// Translations
const baseTranslations = {
    appName: 'MelaVibe',
    attendee: 'Attendee',
    organizer: 'Organizer',
    logoutButton: 'Logout',
    reportViaSms: 'Emergency? Report via SMS',
    smsInstructions: 'For urgent issues, send a text to our safety line.',
    copyNumber: 'Copy Number',
    numberCopied: 'Number Copied!',
    myReports: 'My Reports',
    reportIssue: 'Report an Issue',
    lostAndFound: 'Lost & Found',
    description: 'Description',
    addPhoto: 'Add Photo',
    captureLocation: 'Capture Location',
    locationCaptured: 'Location Captured!',
    photoPreview: 'Photo Preview',
    recordVoice: 'Record a Voice Note',
    startRecording: 'Start Recording',
    stopRecording: 'Stop Recording',
    recording: 'Recording...',
    micPermissionDenied: 'Microphone permission denied. Please enable it in your browser settings.',
    playRecording: 'Your Voice Note',
    anonymousReport: 'Submit this report anonymously',
    anonymousReportNote: 'Anonymous reports cannot be viewed later in "My Reports".',
    reviewReport: 'Review Report',
    reportPreviewTitle: 'Review Your Report',
    yourPhoto: 'Your Photo',
    yourDescription: 'Your Description',
    yourVoiceNote: 'Your Voice Note',
    capturedLocation: 'Location Attached',
    aiAssessment: 'AI Triage',
    aiPriority: 'AI Priority',
    aiSuggestedTeam: 'Suggested Team',
    aiSummary: 'Summary',
    goBackEdit: 'Go Back & Edit',
    confirmSubmit: 'Confirm & Submit',
    reportSuccess: 'Report submitted successfully!',
    issue_MedicalEmergency: 'Medical Emergency',
    issue_SafetyConcern: 'Safety Concern',
    issue_Harassment: 'Harassment',
    issue_TheftProperty: 'Theft / Property',
    issue_LostPerson: 'Lost Person',
    issue_SanitationIssue: 'Sanitation',
    issue_FacilityMaintenance: 'Facilities',
    issue_FireHazard: 'Fire Hazard',
    issue_InfoQuestion: 'Information',
    issue_Other: 'Other',
    team_Medical: 'Medical',
    team_Security: 'Security',
    team_Sanitation: 'Sanitation',
    team_Facilities: 'Facilities',
    team_General: 'General',
    priority_Low: 'Low',
    priority_Medium: 'Medium',
    priority_High: 'High',
    status_NEW: 'New',
    status_IN_PROGRESS: 'In Progress',
    status_RESOLVED: 'Resolved',
    dashboard: 'Organizer Dashboard',
    totalReports: 'Total Reports',
    sortBy: 'Sort by',
    sort_timestamp: 'Most Recent',
    sort_priority: 'Highest Priority',
    gridView: 'Grid',
    mapView: 'Map',
    reportsView: 'Reports',
    crowdDensityView: 'Crowd Density',
    viewOnMap: 'View on Map',
    copyCoordinates: 'Copy Coords',
    coordinatesCopied: 'Copied!',
    addComment: 'Note',
    emptyDashboardTitle: 'All Clear!',
    emptyDashboardMessage: 'There are currently no reports. Everything seems to be running smoothly.',
    emptyFilterTitle: 'No Reports Found',
    emptyFilterMessage: 'No reports match your current filter settings. Try selecting another status.',
    qrTools: 'QR Tools',
    logSmsReport: 'Log SMS Report',
    sendBroadcast: 'Broadcast',
    exportCSV: 'Export CSV',
    analytics: 'Analytics',
    myReportsTitle: 'My Submitted Reports',
    noMyReports: 'You have not submitted any non-anonymous reports.',
    organizerNotes: "Organizer's Notes",
    confirmStatusChangeTitle: 'Confirm Status Change',
    confirmStatusChangeMessage: 'Are you sure you want to change the status of this report to "{status}"?',
    confirmStatusChangeButton: 'Yes, Change Status',
    organizerNote: 'Add Organizer Note',
    addNotePlaceholder: 'Add a comment for other organizers...',
    submitNote: 'Submit Note',
    lostAndFoundHub: "Lost & Found Hub",
    viewFoundItems: "Found Items",
    viewLostItems: "Lost Items",
    iFoundSomething: "I Found Something",
    iLostSomething: "I Lost Something",
    noLfItems: "No items listed yet.",
    lfStatus_FOUND: "Found",
    lfStatus_LOST: "Lost",
    itemCategory: "Item Category",
    selectCategory: "Select a category...",
    category_Phone: "Phone",
    category_Wallet: "Wallet / Cards",
    category_Keys: "Keys",
    category_Bag: "Bag / Backpack",
    category_Clothing: "Clothing",
    category_Other: "Other",
    itemDescription: "Description",
    addAPhoto: "Add a Photo",
    submitItem: "Submit Item",
    unresolvedItems: "Unresolved",
    resolvedItems: "Resolved",
    markAsResolved: "Mark as Claimed/Resolved",
    itemClaimed: "Item Claimed/Resolved",
    lfOrganizerView: "Lost & Found",
    incidentReports: "Incidents",
    analyticsReport: "Event Analytics Report",
    avgResolutionTime: "Avg. Resolution Time",
    minutes: "mins",
    notApplicable: "N/A",
    reportsByType: "Reports by Type",
    reportsByPriority: "Reports by Priority",
    noReportsForAnalytics: "Not enough data to generate analytics.",
    printReport: "Print Report",
    noLocationDataForMap: "No reports with location data to display on the map.",
    viewReport: "View Full Report",
    densityLow: "Low",
    densityMedium: "Medium",
    densityHigh: "High",
    configSetupTitle: "Application Setup Required",
    configSetupPasteInstructions: "To get started, paste your Firebase configuration object below. This is provided in your Firebase project settings.",
    configSetupPasteLabel: "Firebase Config Object",
    configSetupSaveButton: "Save & Initialize",
    configSetupOr: "OR",
    configSetupScanButton: "Scan QR Code from Console",
    configSetupScanInstructions: "Scan the QR code displayed in the event console to configure the app automatically.",
    configSetupFooter: "This configuration is stored locally on your device and is required for the app to connect to the event database.",
    configEmptyError: "Configuration cannot be empty.",
    configParsingError: "Could not parse the configuration. Please paste the full JavaScript object.",
    configSaveError: "Could not save configuration. Please ensure local storage is enabled.",
    invalidQRCode: "The QR code is not a valid configuration.",
    scanError: "An error occurred while scanning.",
    cameraPermissionError: "Camera permission is required to scan QR codes.",
    organizerLoginTitle: "Organizer Login",
    passwordLabel: "Password",
    passwordPlaceholder: "Enter password",
    signInButton: "Sign In",
    incorrectPasswordError: "Incorrect password. Please try again.",
    qrToolsTitle: "QR Code Tools",
    tabShareApp: "Share App",
    tabSyncReports: "Sync Reports",
    tabShareSetup: "Share Setup",
    shareAppInstructions: "Attendees can scan this QR code to open the reporting app on their own devices.",
    syncReportsTitle: "Sync Reports Between Devices",
    syncReportsShareInstructions: "To send reports from this device to another, select the reports you want to share and generate a QR code.",
    startSelection: "Select Reports to Share",
    syncReportsReceiveInstructions: "To receive reports from another device, scan the QR code they have generated.",
    receiveReports: "Scan to Receive Reports",
    shareSetupTitle: "Share Setup Configuration",
    shareSetupInstructions: "Another organizer can scan this to quickly set up their device. This contains sensitive configuration data.",
    configQrWarning: "Warning: This QR code contains sensitive configuration credentials. Do not share it publicly.",
    shareQrDisplayTitle: "Share {count} Report(s)",
    shareQrDisplayInstructions: "Have another organizer scan this QR code using the 'Sync Reports' tool to import these reports to their device.",
    shareQrDisplayNote: "This QR code contains the report data. It will be valid as long as this modal is open.",
    scanSuccess: "Scan successful!",
    reportsImported: "new reports imported",
    logSmsModalTitle: "Log SMS Report",
    logSmsModalInstructions: "Manually enter a report received via SMS message to add it to the dashboard.",
    fullMessageContent: "Full Message Content",
    createReport: "Create Report",
    broadcastModalTitle: "Send Broadcast Announcement",
    broadcastModalInstructions: "This message will appear as a banner at the top of the app for all attendees.",
    broadcastMessage: "Announcement Message",
    send: "Send",
    cancel: "Cancel",
    cancelSelection: "Cancel Selection",
    generateShareQR: "Generate QR for {count} reports",
    weatherWidgetTitle: "Live Weather",
    weatherTemp: "{temp}°C",
    weatherFeelsLike: "Feels like {temp}°C",
    weatherCondition_Clear: "Clear Sky",
    weatherCondition_PartlyCloudy: "Partly Cloudy",
    weatherCondition_Fog: "Fog",
    weatherCondition_Drizzle: "Drizzle",
    weatherCondition_Rain: "Rain",
    weatherCondition_Snow: "Snow",
    weatherCondition_Thunderstorm: "Thunderstorm",
    weatherLoading: "Loading weather...",
    weatherError_locationPermission: "Location access denied. Please enable it to see live weather.",
    weatherError_locationGeneral: "Could not get your location. Weather is unavailable.",
    weatherError_api: "Could not fetch weather data. Please try again later.",
    feedbackView: 'Feedback',
    averageRating: 'Average Rating',
    outOfFive: 'out of 5',
    ratingDistribution: 'Rating Distribution',
    feedbackComments: 'Feedback Comments',
    noFeedbackYetTitle: 'No Feedback Yet',
    noFeedbackYetMessage: 'Once attendees submit feedback, their ratings and comments will appear here.',
};

export const TRANSLATIONS: { [key: string]: { [key: string]: string } } = {
    en: baseTranslations,
    hi: {
        ...baseTranslations,
        appName: 'मेला वाइब',
        attendee: 'उपस्थित',
        organizer: 'आयोजक',
        logoutButton: 'लॉग आउट',
        reportViaSms: 'आपातकाल? SMS द्वारा रिपोर्ट करें',
        smsInstructions: 'अत्यावश्यक मुद्दों के लिए, हमारी सुरक्षा लाइन पर एक टेक्स्ट भेजें।',
        copyNumber: 'नंबर कॉपी करें',
        numberCopied: 'नंबर कॉपी हो गया!',
        myReports: 'मेरी रिपोर्ट',
        reportIssue: 'समस्या की रिपोर्ट करें',
        lostAndFound: 'खोया-पाया',
        description: 'विवरण',
        addPhoto: 'फ़ोटो जोड़ें',
        captureLocation: 'स्थान कैप्चर करें',
        locationCaptured: 'स्थान कैप्चर हो गया!',
        photoPreview: 'फ़ोटो पूर्वावलोकन',
        recordVoice: 'एक वॉयस नोट रिकॉर्ड करें',
        startRecording: 'रिकॉर्डिंग शुरू करें',
        stopRecording: 'रिकॉर्डिंग रोकें',
        recording: 'रिकॉर्डिंग हो रही है...',
        micPermissionDenied: 'माइक्रोफ़ोन की अनुमति अस्वीकार कर दी गई। कृपया अपनी ब्राउज़र सेटिंग्स में इसे सक्षम करें।',
        playRecording: 'आपका वॉयस नोट',
        anonymousReport: 'इस रिपोर्ट को गुमनाम रूप से सबमिट करें',
        anonymousReportNote: 'गुमनाम रिपोर्ट को बाद में "मेरी रिपोर्ट" में नहीं देखा जा सकता।',
        reviewReport: 'रिपोर्ट की समीक्षा करें',
        reportPreviewTitle: 'अपनी रिपोर्ट की समीक्षा करें',
        yourPhoto: 'आपकी फ़ोटो',
        yourDescription: 'आपका विवरण',
        yourVoiceNote: 'आपका वॉयस नोट',
        capturedLocation: 'स्थान संलग्न है',
        aiAssessment: 'AI ट्राइएज',
        aiPriority: 'AI प्राथमिकता',
        aiSuggestedTeam: 'सुझाई गई टीम',
        aiSummary: 'सारांश',
        goBackEdit: 'वापस जाएं और संपादित करें',
        confirmSubmit: 'पुष्टि करें और सबमिट करें',
        reportSuccess: 'रिपोर्ट सफलतापूर्वक सबमिट हो गई!',
        issue_MedicalEmergency: 'चिकित्सा आपातकाल',
        issue_SafetyConcern: 'सुरक्षा चिंता',
        issue_Harassment: 'उत्पीड़न',
        issue_TheftProperty: 'चोरी / संपत्ति',
        issue_LostPerson: 'खोया हुआ व्यक्ति',
        issue_SanitationIssue: 'स्वच्छता',
        issue_FacilityMaintenance: 'सुविधाएं',
        issue_FireHazard: 'आग का खतरा',
        issue_InfoQuestion: 'जानकारी',
        issue_Other: 'अन्य',
        team_Medical: 'चिकित्सा',
        team_Security: 'सुरक्षा',
        team_Sanitation: 'स्वच्छता',
        team_Facilities: 'सुविधाएं',
        team_General: 'सामान्य',
        priority_Low: 'कम',
        priority_Medium: 'मध्यम',
        priority_High: 'उच्च',
        status_NEW: 'नया',
        status_IN_PROGRESS: 'प्रगति में',
        status_RESOLVED: 'हल हो गया',
        dashboard: 'आयोजक डैशबोर्ड',
        totalReports: 'कुल रिपोर्ट',
        sortBy: 'इसके अनुसार क्रमबद्ध करें',
        sort_timestamp: 'सबसे नया',
        sort_priority: 'उच्चतम प्राथमिकता',
        gridView: 'ग्रिड',
        mapView: 'मानचित्र',
        reportsView: 'रिपोर्ट',
        crowdDensityView: 'भीड़ घनत्व',
        viewOnMap: 'मानचित्र पर देखें',
        copyCoordinates: 'निर्देशांक कॉपी करें',
        coordinatesCopied: 'कॉपी हो गया!',
        addComment: 'नोट',
        emptyDashboardTitle: 'सब कुछ साफ़ है!',
        emptyDashboardMessage: 'वर्तमान में कोई रिपोर्ट नहीं है। सब कुछ सुचारू रूप से चल रहा है।',
        emptyFilterTitle: 'कोई रिपोर्ट नहीं मिली',
        emptyFilterMessage: 'कोई भी रिपोर्ट आपकी वर्तमान फ़िल्टर सेटिंग्स से मेल नहीं खाती। कोई अन्य स्थिति चुनने का प्रयास करें।',
        qrTools: 'QR उपकरण',
        logSmsReport: 'SMS रिपोर्ट लॉग करें',
        sendBroadcast: 'प्रसारण',
        exportCSV: 'CSV निर्यात करें',
        analytics: 'विश्लेषिकी',
        myReportsTitle: 'मेरी सबमिट की गई रिपोर्ट',
        noMyReports: 'आपने कोई भी गैर-गुमनाम रिपोर्ट सबमिट नहीं की है।',
        organizerNotes: "आयोजक के नोट्स",
        confirmStatusChangeTitle: 'स्थिति परिवर्तन की पुष्टि करें',
        confirmStatusChangeMessage: 'क्या आप वाकई इस रिपोर्ट की स्थिति को "{status}" में बदलना चाहते हैं?',
        confirmStatusChangeButton: 'हाँ, स्थिति बदलें',
        organizerNote: 'आयोजक नोट जोड़ें',
        addNotePlaceholder: 'अन्य आयोजकों के लिए एक टिप्पणी जोड़ें...',
        submitNote: 'नोट सबमिट करें',
        lostAndFoundHub: "खोया-पाया केंद्र",
        viewFoundItems: "मिली वस्तुएं",
        viewLostItems: "खोई वस्तुएं",
        iFoundSomething: "मुझे कुछ मिला",
        iLostSomething: "मैंने कुछ खो दिया",
        noLfItems: "अभी तक कोई वस्तु सूचीबद्ध नहीं है।",
        lfStatus_FOUND: "मिला",
        lfStatus_LOST: "खोया",
        itemCategory: "वस्तु श्रेणी",
        selectCategory: "एक श्रेणी चुनें...",
        category_Phone: "फ़ोन",
        category_Wallet: "बटुआ / कार्ड",
        category_Keys: "चाबियाँ",
        category_Bag: "बैग / बैकपैक",
        category_Clothing: "कपड़े",
        category_Other: "अन्य",
        itemDescription: "विवरण",
        addAPhoto: "एक फ़ोटो जोड़ें",
        submitItem: "वस्तु सबमिट करें",
        unresolvedItems: "अनसुलझे",
        resolvedItems: "सुलझे हुए",
        markAsResolved: "दावा किया/हल किया गया के रूप में चिह्नित करें",
        itemClaimed: "वस्तु का दावा किया/हल किया गया",
        lfOrganizerView: "खोया-पाया",
        incidentReports: "घटनाएं",
        analyticsReport: "इवेंट एनालिटिक्स रिपोर्ट",
        avgResolutionTime: "औसत समाधान समय",
        minutes: "मिनट",
        notApplicable: "लागू नहीं",
        reportsByType: "प्रकार के अनुसार रिपोर्ट",
        reportsByPriority: "प्राथमिकता के अनुसार रिपोर्ट",
        noReportsForAnalytics: "विश्लेषिकी उत्पन्न करने के लिए पर्याप्त डेटा नहीं है।",
        printReport: "रिपोर्ट प्रिंट करें",
        noLocationDataForMap: "मानचित्र पर प्रदर्शित करने के लिए स्थान डेटा वाली कोई रिपोर्ट नहीं है।",
        viewReport: "पूरी रिपोर्ट देखें",
        densityLow: "कम",
        densityMedium: "मध्यम",
        densityHigh: "उच्च",
        configSetupTitle: "एप्लिकेशन सेटअप आवश्यक है",
        configSetupPasteInstructions: "शुरू करने के लिए, नीचे अपना फायरबेस कॉन्फ़िगरेशन ऑब्जेक्ट पेस्ट करें। यह आपकी फायरबेस प्रोजेक्ट सेटिंग्स में प्रदान किया गया है।",
        configSetupPasteLabel: "फायरबेस कॉन्फ़िग ऑब्जेक्ट",
        configSetupSaveButton: "सहेजें और आरंभ करें",
        configSetupOr: "या",
        configSetupScanButton: "कंसोल से QR कोड स्कैन करें",
        configSetupScanInstructions: "ऐप को स्वचालित रूप से कॉन्फ़िगर करने के लिए इवेंट कंसोल में प्रदर्शित QR कोड को स्कैन करें।",
        configSetupFooter: "यह कॉन्फ़िगरेशन आपके डिवाइस पर स्थानीय रूप से संग्रहीत है और ऐप को इवेंट डेटाबेस से कनेक्ट करने के लिए आवश्यक है।",
        configEmptyError: "कॉन्फ़िगरेशन खाली नहीं हो सकता।",
        configParsingError: "कॉन्फ़िगरेशन को पार्स नहीं किया जा सका। कृपया पूरा जावास्क्रिप्ट ऑब्जेक्ट पेस्ट करें।",
        configSaveError: "कॉन्फ़िगरेशन सहेजा नहीं जा सका। कृपया सुनिश्चित करें कि स्थानीय भंडारण सक्षम है।",
        invalidQRCode: "QR कोड एक वैध कॉन्फ़िगरेशन नहीं है।",
        scanError: "स्कैन करते समय एक त्रुटि हुई।",
        cameraPermissionError: "QR कोड स्कैन करने के लिए कैमरा अनुमति आवश्यक है।",
        organizerLoginTitle: "आयोजक लॉगिन",
        passwordLabel: "पासवर्ड",
        passwordPlaceholder: "पासवर्ड दर्ज करें",
        signInButton: "साइन इन करें",
        incorrectPasswordError: "गलत पासवर्ड। कृपया पुनः प्रयास करें।",
        qrToolsTitle: "QR कोड उपकरण",
        tabShareApp: "ऐप साझा करें",
        tabSyncReports: "रिपोर्ट सिंक करें",
        tabShareSetup: "सेटअप साझा करें",
        shareAppInstructions: "उपस्थित लोग इस QR कोड को स्कैन करके अपने डिवाइस पर रिपोर्टिंग ऐप खोल सकते हैं।",
        syncReportsTitle: "उपकरणों के बीच रिपोर्ट सिंक करें",
        syncReportsShareInstructions: "इस डिवाइस से दूसरे डिवाइस पर रिपोर्ट भेजने के लिए, उन रिपोर्टों का चयन करें जिन्हें आप साझा करना चाहते हैं और एक QR कोड उत्पन्न करें।",
        startSelection: "साझा करने के लिए रिपोर्ट चुनें",
        syncReportsReceiveInstructions: "दूसरे डिवाइस से रिपोर्ट प्राप्त करने के लिए, उनके द्वारा उत्पन्न QR कोड को स्कैन करें।",
        receiveReports: "रिपोर्ट प्राप्त करने के लिए स्कैन करें",
        shareSetupTitle: "सेटअप कॉन्फ़िगरेशन साझा करें",
        shareSetupInstructions: "कोई अन्य आयोजक अपने डिवाइस को जल्दी से सेट करने के लिए इसे स्कैन कर सकता है। इसमें संवेदनशील कॉन्फ़िगरेशन डेटा होता है।",
        configQrWarning: "चेतावनी: इस QR कोड में संवेदनशील कॉन्फ़िगरेशन क्रेडेंशियल हैं। इसे सार्वजनिक रूप से साझा न करें।",
        shareQrDisplayTitle: "{count} रिपोर्ट साझा करें",
        shareQrDisplayInstructions: "इन रिपोर्टों को अपने डिवाइस पर आयात करने के लिए किसी अन्य आयोजक से 'सिंक रिपोर्ट' टूल का उपयोग करके इस QR कोड को स्कैन करवाएं।",
        shareQrDisplayNote: "इस QR कोड में रिपोर्ट डेटा है। यह तब तक मान्य रहेगा जब तक यह मोडल खुला है।",
        scanSuccess: "स्कैन सफल!",
        reportsImported: "नई रिपोर्ट आयात की गईं",
        logSmsModalTitle: "SMS रिपोर्ट लॉग करें",
        logSmsModalInstructions: "डैशबोर्ड में जोड़ने के लिए SMS संदेश के माध्यम से प्राप्त एक रिपोर्ट को मैन्युअल रूप से दर्ज करें।",
        fullMessageContent: "पूरा संदेश सामग्री",
        createReport: "रिपोर्ट बनाएं",
        broadcastModalTitle: "प्रसारण घोषणा भेजें",
        broadcastModalInstructions: "यह संदेश सभी उपस्थित लोगों के लिए ऐप के शीर्ष पर एक बैनर के रूप में दिखाई देगा।",
        broadcastMessage: "घोषणा संदेश",
        send: "भेजें",
        cancel: "रद्द करें",
        cancelSelection: "चयन रद्द करें",
        generateShareQR: "{count} रिपोर्ट के लिए QR उत्पन्न करें",
        weatherWidgetTitle: "लाइव मौसम",
        weatherTemp: "{temp}°C",
        weatherFeelsLike: "{temp}°C जैसा महसूस होता है",
        weatherCondition_Clear: "साफ आकाश",
        weatherCondition_PartlyCloudy: "आंशिक रूप से बादल छाए हुए",
        weatherCondition_Fog: "कोहरा",
        weatherCondition_Drizzle: "बूंदा बांदी",
        weatherCondition_Rain: "बारिश",
        weatherCondition_Snow: "हिमपात",
        weatherCondition_Thunderstorm: "आंधी",
        weatherLoading: "मौसम लोड हो रहा है...",
        weatherError_locationPermission: "स्थान की अनुमति अस्वीकृत। लाइव मौसम देखने के लिए कृपया इसे सक्षम करें।",
        weatherError_locationGeneral: "आपका स्थान प्राप्त नहीं हो सका। मौसम अनुपलब्ध है।",
        weatherError_api: "मौसम डेटा प्राप्त नहीं किया जा सका। कृपया बाद में पुनः प्रयास करें।",
        feedbackView: 'प्रतिक्रिया',
        averageRating: 'औसत रेटिंग',
        outOfFive: '5 में से',
        ratingDistribution: 'रेटिंग वितरण',
        feedbackComments: 'प्रतिक्रिया टिप्पणियाँ',
        noFeedbackYetTitle: 'अभी तक कोई प्रतिक्रिया नहीं',
        noFeedbackYetMessage: 'एक बार जब उपस्थित लोग प्रतिक्रिया सबमिट कर देंगे, तो उनकी रेटिंग और टिप्पणियाँ यहाँ दिखाई देंगी।',
    },
    te: {
        ...baseTranslations,
        appName: 'మేళా వైబ్',
        attendee: 'హాజరైనవారు',
        organizer: 'నిర్వాహకుడు',
        logoutButton: 'లాగ్ అవుట్',
        reportViaSms: 'అత్యవసరమా? SMS ద్వారా నివేదించండి',
        smsInstructions: 'అత్యవసర సమస్యల కోసం, మా భద్రతా లైన్‌కు టెక్స్ట్ పంపండి.',
        copyNumber: 'నెంబర్ కాపీ చేయండి',
        numberCopied: 'నెంబర్ కాపీ చేయబడింది!',
        myReports: 'నా నివేదికలు',
        reportIssue: 'సమస్యను నివేదించండి',
        lostAndFound: 'లాస్ట్ & ఫౌండ్',
        description: 'వివరణ',
        addPhoto: 'ఫోటో జోడించండి',
        captureLocation: 'స్థానాన్ని క్యాప్చర్ చేయండి',
        locationCaptured: 'స్థానం క్యాప్చర్ చేయబడింది!',
        photoPreview: 'ఫోటో ప్రివ్యూ',
        recordVoice: 'వాయిస్ నోట్ రికార్డ్ చేయండి',
        startRecording: 'రికార్డింగ్ ప్రారంభించండి',
        stopRecording: 'రికార్డింగ్ ఆపండి',
        recording: 'రికార్డింగ్ జరుగుతోంది...',
        micPermissionDenied: 'మైక్రోఫోన్ అనుమతి నిరాకరించబడింది. దయచేసి మీ బ్రౌజర్ సెట్టింగ్‌లలో దీన్ని ప్రారంభించండి.',
        playRecording: 'మీ వాయిస్ నోట్',
        anonymousReport: 'ఈ నివేదికను అనామకంగా సమర్పించండి',
        anonymousReportNote: 'అనామక నివేదికలను తర్వాత "నా నివేదికలు"లో చూడలేరు.',
        reviewReport: 'నివేదికను సమీక్షించండి',
        reportPreviewTitle: 'మీ నివేదికను సమీక్షించండి',
        yourPhoto: 'మీ ఫోటో',
        yourDescription: 'మీ వివరణ',
        yourVoiceNote: 'మీ వాయిస్ నోట్',
        capturedLocation: 'స్థానం జోడించబడింది',
        aiAssessment: 'AI ట్రయేజ్',
        aiPriority: 'AI ప్రాధాన్యత',
        aiSuggestedTeam: 'సూచించిన బృందం',
        aiSummary: 'సారాంశం',
        goBackEdit: 'వెనక్కి వెళ్లి సవరించండి',
        confirmSubmit: 'నిర్ధారించి సమర్పించండి',
        reportSuccess: 'నివేదిక విజయవంతంగా సమర్పించబడింది!',
        issue_MedicalEmergency: 'వైద్య అత్యవసర పరిస్థితి',
        issue_SafetyConcern: 'భద్రతా ఆందోళన',
        issue_Harassment: 'వేధింపులు',
        issue_TheftProperty: 'దొంగతనం / ఆస్తి',
        issue_LostPerson: 'తప్పిపోయిన వ్యక్తి',
        issue_SanitationIssue: 'పారిశుధ్యం',
        issue_FacilityMaintenance: 'సౌకర్యాలు',
        issue_FireHazard: 'అగ్ని ప్రమాదం',
        issue_InfoQuestion: 'సమాచారం',
        issue_Other: 'ఇతర',
        team_Medical: 'వైద్య',
        team_Security: 'భద్రత',
        team_Sanitation: 'పారిశుధ్యం',
        team_Facilities: 'సౌకర్యాలు',
        team_General: 'సాధారణ',
        priority_Low: 'తక్కువ',
        priority_Medium: 'మధ్యస్థం',
        priority_High: 'అధిక',
        status_NEW: 'కొత్త',
        status_IN_PROGRESS: 'ప్రోగ్రెస్‌లో ఉంది',
        status_RESOLVED: 'పరిష్కరించబడింది',
        dashboard: 'నిర్వాహక డాష్‌బోర్డ్',
        totalReports: 'మొత్తం నివేదికలు',
        sortBy: 'దీని ప్రకారం క్రమబద్ధీకరించు',
        sort_timestamp: 'అత్యంత ఇటీవలి',
        sort_priority: 'అత్యధిక ప్రాధాన్యత',
        gridView: 'గ్రిడ్',
        mapView: 'మ్యాప్',
        reportsView: 'నివేదికలు',
        crowdDensityView: 'జన సాంద్రత',
        viewOnMap: 'మ్యాప్‌లో చూడండి',
        copyCoordinates: 'కోఆర్డినేట్‌లను కాపీ చేయండి',
        coordinatesCopied: 'కాపీ చేయబడింది!',
        addComment: 'గమనిక',
        emptyDashboardTitle: 'అన్నీ స్పష్టంగా ఉన్నాయి!',
        emptyDashboardMessage: 'ప్రస్తుతం నివేదికలు లేవు. అంతా సజావుగా సాగుతున్నట్లుంది.',
        emptyFilterTitle: 'నివేదికలు కనుగొనబడలేదు',
        emptyFilterMessage: 'మీ ప్రస్తుత ఫిల్టర్ సెట్టింగ్‌లతో ఏ నివేదికలూ సరిపోలలేదు. మరొక స్థితిని ఎంచుకోవడానికి ప్రయత్నించండి.',
        qrTools: 'QR సాధనాలు',
        logSmsReport: 'SMS నివేదికను లాగ్ చేయండి',
        sendBroadcast: 'ప్రసారం',
        exportCSV: 'CSVని ఎగుమతి చేయండి',
        analytics: 'విశ్లేషణలు',
        myReportsTitle: 'నేను సమర్పించిన నివేదికలు',
        noMyReports: 'మీరు అనామకం కాని నివేదికలను సమర్పించలేదు.',
        organizerNotes: "నిర్వాహకుడి గమనికలు",
        confirmStatusChangeTitle: 'స్థితి మార్పును నిర్ధారించండి',
        confirmStatusChangeMessage: 'మీరు నిజంగా ఈ నివేదిక స్థితిని "{status}"కి మార్చాలనుకుంటున్నారా?',
        confirmStatusChangeButton: 'అవును, స్థితిని మార్చండి',
        organizerNote: 'నిర్వాహకుడి గమనికను జోడించండి',
        addNotePlaceholder: 'ఇతర నిర్వాహకుల కోసం ఒక వ్యాఖ్యను జోడించండి...',
        submitNote: 'గమనికను సమర్పించండి',
        lostAndFoundHub: "లాస్ట్ & ఫౌండ్ హబ్",
        viewFoundItems: "దొరికిన వస్తువులు",
        viewLostItems: "పోయిన వస్తువులు",
        iFoundSomething: "నాకు ఒకటి దొరికింది",
        iLostSomething: "నేను ఒకటి పోగొట్టుకున్నాను",
        noLfItems: "ఇంకా ఏ వస్తువులూ జాబితా చేయబడలేదు.",
        lfStatus_FOUND: "దొరికింది",
        lfStatus_LOST: "పోయింది",
        itemCategory: "వస్తువు వర్గం",
        selectCategory: "ఒక వర్గాన్ని ఎంచుకోండి...",
        category_Phone: "ఫోన్",
        category_Wallet: "వాలెట్ / కార్డులు",
        category_Keys: "కీలు",
        category_Bag: "బ్యాగ్ / బ్యాక్‌ప్యాక్",
        category_Clothing: "బట్టలు",
        category_Other: "ఇతర",
        itemDescription: "వివరణ",
        addAPhoto: "ఒక ఫోటోను జోడించండి",
        submitItem: "వస్తువును సమర్పించండి",
        unresolvedItems: "పరిష్కరించనివి",
        resolvedItems: "పరిష్కరించినవి",
        markAsResolved: "దావా చేయబడినది/పరిష్కరించబడినదిగా గుర్తించండి",
        itemClaimed: "వస్తువు దావా చేయబడింది/పరిష్కరించబడింది",
        lfOrganizerView: "లాస్ట్ & ఫౌండ్",
        incidentReports: "సంఘటనలు",
        analyticsReport: "ఈవెంట్ విశ్లేషణల నివేదిక",
        avgResolutionTime: "సగటు పరిష్కార సమయం",
        minutes: "నిమిషాలు",
        notApplicable: "వర్తించదు",
        reportsByType: "రకం వారీగా నివేదికలు",
        reportsByPriority: "ప్రాధాన్యత వారీగా నివేదికలు",
        noReportsForAnalytics: "విశ్లేషణలను రూపొందించడానికి తగినంత డేటా లేదు.",
        printReport: "నివేదికను ముద్రించండి",
        noLocationDataForMap: "మ్యాప్‌లో ప్రదర్శించడానికి స్థాన డేటాతో నివేదికలు లేవు.",
        viewReport: "పూర్తి నివేదికను చూడండి",
        densityLow: "తక్కువ",
        densityMedium: "మధ్యస్థం",
        densityHigh: "అధిక",
        configSetupTitle: "అప్లికేషన్ సెటప్ అవసరం",
        configSetupPasteInstructions: "ప్రారంభించడానికి, మీ Firebase కాన్ఫిగరేషన్ ఆబ్జెక్ట్‌ను కింద అతికించండి. ఇది మీ Firebase ప్రాజెక్ట్ సెట్టింగ్‌లలో అందించబడింది.",
        configSetupPasteLabel: "Firebase కాన్ఫిగ్ ఆబ్జెక్ట్",
        configSetupSaveButton: "సేవ్ చేసి ప్రారంభించండి",
        configSetupOr: "లేదా",
        configSetupScanButton: "కన్సోల్ నుండి QR కోడ్‌ను స్కాన్ చేయండి",
        configSetupScanInstructions: "యాప్‌ను స్వయంచాలకంగా కాన్ఫిగర్ చేయడానికి ఈవెంట్ కన్సోల్‌లో ప్రదర్శించబడిన QR కోడ్‌ను స్కాన్ చేయండి.",
        configSetupFooter: "ఈ కాన్ఫిగరేషన్ మీ పరికరంలో స్థానికంగా నిల్వ చేయబడుతుంది మరియు ఈవెంట్ డేటాబేస్‌కు కనెక్ట్ అవ్వడానికి యాప్‌కు అవసరం.",
        configEmptyError: "కాన్ఫిగరేషన్ ఖాళీగా ఉండకూడదు.",
        configParsingError: "కాన్ఫిగరేషన్‌ను పార్స్ చేయలేకపోయాము. దయచేసి పూర్తి జావాస్క్రిప్ట్ ఆబ్జెక్ట్‌ను అతికించండి.",
        configSaveError: "కాన్ఫిగరేషన్‌ను సేవ్ చేయలేకపోయాము. దయచేసి స్థానిక నిల్వ ప్రారంభించబడిందని నిర్ధారించుకోండి.",
        invalidQRCode: "QR కోడ్ చెల్లుబాటు అయ్యే కాన్ఫిగరేషన్ కాదు.",
        scanError: "స్కాన్ చేసేటప్పుడు ఒక లోపం సంభవించింది.",
        cameraPermissionError: "QR కోడ్‌లను స్కాన్ చేయడానికి కెమెరా అనుమతి అవసరం.",
        organizerLoginTitle: "నిర్వాహకుడి లాగిన్",
        passwordLabel: "పాస్‌వర్డ్",
        passwordPlaceholder: "పాస్‌వర్డ్ నమోదు చేయండి",
        signInButton: "సైన్ ఇన్ చేయండి",
        incorrectPasswordError: "తప్పు పాస్‌వర్డ్. దయచేసి మళ్లీ ప్రయత్నించండి.",
        qrToolsTitle: "QR కోడ్ సాధనాలు",
        tabShareApp: "యాప్‌ను షేర్ చేయండి",
        tabSyncReports: "నివేదికలను సింక్ చేయండి",
        tabShareSetup: "సెటప్‌ను షేర్ చేయండి",
        shareAppInstructions: "హాజరైనవారు ఈ QR కోడ్‌ను స్కాన్ చేసి వారి స్వంత పరికరాల్లో రిపోర్టింగ్ యాప్‌ను తెరవగలరు.",
        syncReportsTitle: "పరికరాల మధ్య నివేదికలను సింక్ చేయండి",
        syncReportsShareInstructions: "ఈ పరికరం నుండి మరొక పరికరానికి నివేదికలను పంపడానికి, మీరు షేర్ చేయాలనుకుంటున్న నివేదికలను ఎంచుకుని, ఒక QR కోడ్‌ను రూపొందించండి.",
        startSelection: "షేర్ చేయడానికి నివేదికలను ఎంచుకోండి",
        syncReportsReceiveInstructions: "మరొక పరికరం నుండి నివేదికలను స్వీకరించడానికి, వారు రూపొందించిన QR కోడ్‌ను స్కాన్ చేయండి.",
        receiveReports: "నివేదికలను స్వీకరించడానికి స్కాన్ చేయండి",
        shareSetupTitle: "సెటప్ కాన్ఫిగరేషన్‌ను షేర్ చేయండి",
        shareSetupInstructions: "మరొక నిర్వాహకుడు వారి పరికరాన్ని త్వరగా సెటప్ చేయడానికి దీన్ని స్కాన్ చేయవచ్చు. ఇందులో సున్నితమైన కాన్ఫిగరేషన్ డేటా ఉంటుంది.",
        configQrWarning: "హెచ్చరిక: ఈ QR కోడ్‌లో సున్నితమైన కాన్ఫిగరేషన్ ఆధారాలు ఉన్నాయి. దీన్ని బహిరంగంగా షేర్ చేయవద్దు.",
        shareQrDisplayTitle: "{count} నివేదిక(లు) షేర్ చేయండి",
        shareQrDisplayInstructions: "ఈ నివేదికలను వారి పరికరంలోకి దిగుమతి చేసుకోవడానికి 'నివేదికలను సింక్ చేయండి' సాధనాన్ని ఉపయోగించి ఈ QR కోడ్‌ను స్కాన్ చేయమని మరొక నిర్వాహకుడికి చెప్పండి.",
        shareQrDisplayNote: "ఈ QR కోడ్‌లో నివేదిక డేటా ఉంటుంది. ఈ మోడల్ తెరిచి ఉన్నంత కాలం ఇది చెల్లుబాటులో ఉంటుంది.",
        scanSuccess: "స్కాన్ విజయవంతమైంది!",
        reportsImported: "కొత్త నివేదికలు దిగుమతి చేయబడ్డాయి",
        logSmsModalTitle: "SMS నివేదికను లాగ్ చేయండి",
        logSmsModalInstructions: "SMS సందేశం ద్వారా అందిన నివేదికను డాష్‌బోర్డ్‌కు జోడించడానికి మాన్యువల్‌గా నమోదు చేయండి.",
        fullMessageContent: "పూర్తి సందేశ కంటెంట్",
        createReport: "నివేదికను సృష్టించండి",
        broadcastModalTitle: "ప్రసార ప్రకటన పంపండి",
        broadcastModalInstructions: "ఈ సందేశం హాజరైన వారందరికీ యాప్ ఎగువన బ్యానర్‌గా కనిపిస్తుంది.",
        broadcastMessage: "ప్రకటన సందేశం",
        send: "పంపండి",
        cancel: "రద్దు చేయి",
        cancelSelection: "ఎంపికను రద్దు చేయండి",
        generateShareQR: "{count} నివేదికల కోసం QRని రూపొందించండి",
        weatherWidgetTitle: "ప్రత్యక్ష వాతావరణం",
        weatherTemp: "{temp}°C",
        weatherFeelsLike: "{temp}°C లా అనిపిస్తుంది",
        weatherCondition_Clear: "స్పష్టమైన ఆకాశం",
        weatherCondition_PartlyCloudy: "పాక్షికంగా మేఘావృతం",
        weatherCondition_Fog: "పొగమంచు",
        weatherCondition_Drizzle: "చినుకులు",
        weatherCondition_Rain: "వర్షం",
        weatherCondition_Snow: "మంచు",
        weatherCondition_Thunderstorm: "ఉరుములతో కూడిన తుఫాను",
        weatherLoading: "వాతావరణం లోడ్ అవుతోంది...",
        weatherError_locationPermission: "స్థాన ప్రాప్యత నిరాకరించబడింది. ప్రత్యక్ష వాతావరణాన్ని చూడటానికి దయచేసి దీన్ని ప్రారంభించండి.",
        weatherError_locationGeneral: "మీ స్థానాన్ని పొందలేకపోయాము. వాతావరణం అందుబాటులో లేదు.",
        weatherError_api: "వాతావరణ డేటాను పొందలేకపోయాము. దయచేసి తర్వాత మళ్లీ ప్రయత్నించండి.",
        feedbackView: 'అభిప్రాయం',
        averageRating: 'సగటు రేటింగ్',
        outOfFive: '5కి',
        ratingDistribution: 'రేటింగ్ పంపిణీ',
        feedbackComments: 'అభిప్రాయ వ్యాఖ్యలు',
        noFeedbackYetTitle: 'ఇంకా అభిప్రాయం లేదు',
        noFeedbackYetMessage: 'హాజరైనవారు అభిప్రాయాన్ని సమర్పించిన తర్వాత, వారి రేటింగ్‌లు మరియు వ్యాఖ్యలు ఇక్కడ కనిపిస్తాయి.',
    },
    bn: {
      ...baseTranslations,
      appName: 'মেলাভাইব',
      attendee: 'উপস্থিত',
      organizer: 'আয়োজক',
      logoutButton: 'লগ আউট',
      reportViaSms: 'জরুরী? এসএমএস এর মাধ্যমে রিপোর্ট করুন',
      smsInstructions: 'জরুরী সমস্যার জন্য, আমাদের সুরক্ষা লাইনে একটি টেক্সট পাঠান।',
      copyNumber: 'নম্বর কপি করুন',
      numberCopied: 'নম্বর কপি করা হয়েছে!',
      myReports: 'আমার রিপোর্ট',
      reportIssue: 'সমস্যার রিপোর্ট করুন',
      lostAndFound: 'হারানো এবং প্রাপ্তি',
      description: 'বিবরণ',
      addPhoto: 'ছবি যোগ করুন',
      captureLocation: 'অবস্থান ক্যাপচার করুন',
      locationCaptured: 'অবস্থান ক্যাপচার করা হয়েছে!',
      photoPreview: 'ছবির পূর্বরূপ',
      recordVoice: 'ভয়েস নোট রেকর্ড করুন',
      startRecording: 'রেকর্ডিং শুরু করুন',
      stopRecording: 'রেকর্ডিং বন্ধ করুন',
      recording: 'রেকর্ডিং চলছে...',
      micPermissionDenied: 'মাইক্রোফোনের অনুমতি প্রত্যাখ্যান করা হয়েছে। অনুগ্রহ করে আপনার ব্রাউজার সেটিংসে এটি সক্ষম করুন।',
      playRecording: 'আপনার ভয়েস নোট',
      anonymousReport: 'এই রিপোর্টটি বেনামে জমা দিন',
      anonymousReportNote: 'বেনামী রিপোর্টগুলি পরে "আমার রিপোর্ট" এ দেখা যাবে না।',
      reviewReport: 'রিপোর্ট পর্যালোচনা করুন',
      reportPreviewTitle: 'আপনার রিপোর্ট পর্যালোচনা করুন',
      yourPhoto: 'আপনার ছবি',
      yourDescription: 'আপনার বিবরণ',
      yourVoiceNote: 'আপনার ভয়েস নোট',
      capturedLocation: 'অবস্থান সংযুক্ত',
      aiAssessment: 'এআই ট্রায়াজ',
      aiPriority: 'এআই অগ্রাধিকার',
      aiSuggestedTeam: 'প্রস্তাবিত দল',
      aiSummary: 'সারাংশ',
      goBackEdit: 'ফিরে যান এবং সম্পাদনা করুন',
      confirmSubmit: 'নিশ্চিত করুন এবং জমা দিন',
      reportSuccess: 'রিপোর্ট সফলভাবে জমা দেওয়া হয়েছে!',
      issue_MedicalEmergency: 'চিকিৎসা জরুরী',
      issue_SafetyConcern: 'নিরাপত্তা উদ্বেগ',
      issue_Harassment: 'হয়রানি',
      issue_TheftProperty: 'চুরি / সম্পত্তি',
      issue_LostPerson: 'হারিয়ে যাওয়া ব্যক্তি',
      issue_SanitationIssue: 'পরিচ্ছন্নতা',
      issue_FacilityMaintenance: 'সুবিধা',
      issue_FireHazard: 'আগুনের ঝুঁকি',
      issue_InfoQuestion: 'তথ্য',
      issue_Other: 'অন্যান্য',
      team_Medical: 'চিকিৎসা',
      team_Security: 'নিরাপত্তা',
      team_Sanitation: 'পরিচ্ছন্নতা',
      team_Facilities: 'সুবিধা',
      team_General: 'সাধারণ',
      priority_Low: 'নিম্ন',
      priority_Medium: 'মাঝারি',
      priority_High: 'উচ্চ',
      status_NEW: 'নতুন',
      status_IN_PROGRESS: 'চলমান',
      status_RESOLVED: 'সমাধান হয়েছে',
      dashboard: 'আয়োজক ড্যাশবোর্ড',
      totalReports: 'মোট রিপোর্ট',
      sortBy: 'সাজান',
      sort_timestamp: 'সাম্প্রতিক',
      sort_priority: 'সর্বোচ্চ অগ্রাধিকার',
      gridView: 'গ্রিড',
      mapView: 'মানচিত্র',
      reportsView: 'রিপোর্ট',
      crowdDensityView: 'ভিড়ের ঘনত্ব',
      viewOnMap: 'মানচিত্রে দেখুন',
      copyCoordinates: 'স্থানাঙ্ক কপি করুন',
      coordinatesCopied: 'কপি করা হয়েছে!',
      addComment: 'নোট',
      emptyDashboardTitle: 'সবকিছু পরিষ্কার!',
      emptyDashboardMessage: 'বর্তমানে কোন রিপোর্ট নেই। সবকিছু মসৃণভাবে চলছে বলে মনে হচ্ছে।',
      emptyFilterTitle: 'কোন রিপোর্ট পাওয়া যায়নি',
      emptyFilterMessage: 'কোন রিপোর্ট আপনার বর্তমান ফিল্টার সেটিংসের সাথে মেলে না। অন্য একটি স্থিতি নির্বাচন করার চেষ্টা করুন।',
      qrTools: 'কিউআর টুলস',
      logSmsReport: 'এসএমএস রিপোর্ট লগ করুন',
      sendBroadcast: 'ব্রডকাস্ট',
      exportCSV: 'সিএসভি এক্সপোর্ট করুন',
      analytics: 'বিশ্লেষণ',
      myReportsTitle: 'আমার জমা দেওয়া রিপোর্ট',
      noMyReports: 'আপনি কোনো বেনামী নয় এমন রিপোর্ট জমা দেননি।',
      organizerNotes: "আয়োজকের নোট",
      confirmStatusChangeTitle: 'স্থিতি পরিবর্তনের বিষয়টি নিশ্চিত করুন',
      confirmStatusChangeMessage: 'আপনি কি নিশ্চিত যে আপনি এই রিপোর্টের স্থিতি "{status}" এ পরিবর্তন করতে চান?',
      confirmStatusChangeButton: 'হ্যাঁ, স্থিতি পরিবর্তন করুন',
      organizerNote: 'আয়োজকের নোট যোগ করুন',
      addNotePlaceholder: 'অন্যান্য আয়োজকদের জন্য একটি মন্তব্য যোগ করুন...',
      submitNote: 'নোট জমা দিন',
      lostAndFoundHub: "হারানো এবং প্রাপ্তি কেন্দ্র",
      viewFoundItems: "পাওয়া জিনিস",
      viewLostItems: "হারানো জিনিস",
      iFoundSomething: "আমি কিছু খুঁজে পেয়েছি",
      iLostSomething: "আমি কিছু হারিয়েছি",
      noLfItems: "এখনও কোন আইটেম তালিকাভুক্ত করা হয়নি।",
      lfStatus_FOUND: "পাওয়া গেছে",
      lfStatus_LOST: "হারিয়েছে",
      itemCategory: "আইটেম বিভাগ",
      selectCategory: "একটি বিভাগ নির্বাচন করুন...",
      category_Phone: "ফোন",
      category_Wallet: "ওয়ালেট / কার্ড",
      category_Keys: "চাবি",
      category_Bag: "ব্যাগ / ব্যাকপ্যাক",
      category_Clothing: "পোশাক",
      category_Other: "অন্যান্য",
      itemDescription: "বিবরণ",
      addAPhoto: "একটি ছবি যোগ করুন",
      submitItem: "আইটেম জমা দিন",
      unresolvedItems: "অমীমাংসিত",
      resolvedItems: "মীমাংসিত",
      markAsResolved: "দাবি করা/মীমাংসিত হিসাবে চিহ্নিত করুন",
      itemClaimed: "আইটেম দাবি করা/মীমাংসিত",
      lfOrganizerView: "হারানো এবং প্রাপ্তি",
      incidentReports: "ঘটনা",
      analyticsReport: "ইভেন্ট অ্যানালিটিক্স রিপোর্ট",
      avgResolutionTime: "গড় সমাধান সময়",
      minutes: "মিনিট",
      notApplicable: "প্রযোজ্য নয়",
      reportsByType: "প্রকার অনুযায়ী রিপোর্ট",
      reportsByPriority: "অগ্রাধিকার অনুযায়ী রিপোর্ট",
      noReportsForAnalytics: "বিশ্লেষণ তৈরির জন্য পর্যাপ্ত ডেটা নেই।",
      printReport: "রিপোর্ট প্রিন্ট করুন",
      noLocationDataForMap: "মানচিত্রে প্রদর্শনের জন্য অবস্থান ডেটা সহ কোন রিপোর্ট নেই।",
      viewReport: "সম্পূর্ণ রিপোর্ট দেখুন",
      densityLow: "কম",
      densityMedium: "মাঝারি",
      densityHigh: "উচ্চ",
      configSetupTitle: "অ্যাপ্লিকেশন সেটআপ প্রয়োজন",
      configSetupPasteInstructions: "শুরু করতে, নিচে আপনার ফায়ারবেস কনফিগারেশন অবজেক্টটি পেস্ট করুন। এটি আপনার ফায়ারবেস প্রকল্প সেটিংসে প্রদান করা হয়েছে।",
      configSetupPasteLabel: "ফায়ারবেস কনফিগ অবজেক্ট",
      configSetupSaveButton: "সংরক্ষণ করুন এবং শুরু করুন",
      configSetupOr: "অথবা",
      configSetupScanButton: "কনসোল থেকে কিউআর কোড স্ক্যান করুন",
      configSetupScanInstructions: "অ্যাপটি স্বয়ংক্রিয়ভাবে কনফিগার করতে ইভেন্ট কনসোলে প্রদর্শিত কিউআর কোডটি স্ক্যান করুন।",
      configSetupFooter: "এই কনফিগারেশনটি আপনার ডিভাইসে স্থানীয়ভাবে সংরক্ষণ করা হয় এবং অ্যাপটিকে ইভেন্ট ডাটাবেসের সাথে সংযোগ করতে প্রয়োজন।",
      configEmptyError: "কনফিগারেশন খালি হতে পারে না।",
      configParsingError: "কনফিগারেশন পার্স করা যায়নি। অনুগ্রহ করে সম্পূর্ণ জাভাস্ক্রিপ্ট অবজেক্টটি পেস্ট করুন।",
      configSaveError: "কনফিগারেশন সংরক্ষণ করা যায়নি। অনুগ্রহ করে নিশ্চিত করুন যে স্থানীয় স্টোরেজ সক্ষম আছে।",
      invalidQRCode: "কিউআর কোডটি একটি বৈধ কনফিগারেশন নয়।",
      scanError: "স্ক্যান করার সময় একটি ত্রুটি ঘটেছে।",
      cameraPermissionError: "কিউআর কোড স্ক্যান করার জন্য ক্যামেরার অনুমতি প্রয়োজন।",
      organizerLoginTitle: "আয়োজক লগইন",
      passwordLabel: "পাসওয়ার্ড",
      passwordPlaceholder: "পাসওয়ার্ড লিখুন",
      signInButton: "সাইন ইন করুন",
      incorrectPasswordError: "ভুল পাসওয়ার্ড। আবার চেষ্টা করুন।",
      qrToolsTitle: "কিউআর কোড টুলস",
      tabShareApp: "অ্যাপ শেয়ার করুন",
      tabSyncReports: "রিপোর্ট সিঙ্ক করুন",
      tabShareSetup: "সেটআপ শেয়ার করুন",
      shareAppInstructions: "উপস্থিত ব্যক্তিরা এই কিউআর কোডটি স্ক্যান করে তাদের নিজস্ব ডিভাইসে রিপোর্টিং অ্যাপটি খুলতে পারেন।",
      syncReportsTitle: "ডিভাইসগুলির মধ্যে রিপোর্ট সিঙ্ক করুন",
      syncReportsShareInstructions: "এই ডিভাইস থেকে অন্য ডিভাইসে রিপোর্ট পাঠাতে, আপনি যে রিপোর্টগুলি শেয়ার করতে চান তা নির্বাচন করুন এবং একটি কিউআর কোড তৈরি করুন।",
      startSelection: "শেয়ার করার জন্য রিপোর্ট নির্বাচন করুন",
      syncReportsReceiveInstructions: "অন্য ডিভাইস থেকে রিপোর্ট পেতে, তাদের তৈরি করা কিউআর কোডটি স্ক্যান করুন।",
      receiveReports: "রিপোর্ট পেতে স্ক্যান করুন",
      shareSetupTitle: "সেটআপ কনফিগারেশন শেয়ার করুন",
      shareSetupInstructions: "অন্য একজন আয়োজক দ্রুত তাদের ডিভাইস সেট আপ করতে এটি স্ক্যান করতে পারেন। এতে সংবেদনশীল কনফিগারেশন ডেটা রয়েছে।",
      configQrWarning: "সতর্কতা: এই কিউআর কোডে সংবেদনশীল কনফিগারেশন শংসাপত্র রয়েছে। এটি সর্বজনীনভাবে শেয়ার করবেন না।",
      shareQrDisplayTitle: "{count}টি রিপোর্ট শেয়ার করুন",
      shareQrDisplayInstructions: "অন্য একজন আয়োজককে 'রিপোর্ট সিঙ্ক করুন' টুল ব্যবহার করে এই কিউআর কোডটি স্ক্যান করতে বলুন যাতে এই রিপোর্টগুলি তাদের ডিভাইসে আমদানি করা যায়।",
      shareQrDisplayNote: "এই কিউআর কোডে রিপোর্ট ডেটা রয়েছে। এই মোডালটি খোলা থাকা পর্যন্ত এটি বৈধ থাকবে।",
      scanSuccess: "স্ক্যান সফল!",
      reportsImported: "নতুন রিপোর্ট আমদানি করা হয়েছে",
      logSmsModalTitle: "এসএমএস রিপোর্ট লগ করুন",
      logSmsModalInstructions: "ড্যাশবোর্ডে যোগ করার জন্য এসএমএস বার্তার মাধ্যমে প্রাপ্ত একটি রিপোর্ট ম্যানুয়ালি প্রবেশ করান।",
      fullMessageContent: "সম্পূর্ণ বার্তা সামগ্রী",
      createReport: "রিপোর্ট তৈরি করুন",
      broadcastModalTitle: "ব্রডকাস্ট ঘোষণা পাঠান",
      broadcastModalInstructions: "এই বার্তাটি সমস্ত উপস্থিতদের জন্য অ্যাপের শীর্ষে একটি ব্যানার হিসাবে উপস্থিত হবে।",
      broadcastMessage: "ঘোষণা বার্তা",
      send: "পাঠান",
      cancel: "বাতিল করুন",
      cancelSelection: "নির্বাচন বাতিল করুন",
      generateShareQR: "{count}টি রিপোর্টের জন্য কিউআর তৈরি করুন",
      weatherWidgetTitle: "লাইভ আবহাওয়া",
      weatherTemp: "{temp}°C",
      weatherFeelsLike: "{temp}°C এর মতো লাগছে",
      weatherCondition_Clear: "পরিষ্কার আকাশ",
      weatherCondition_PartlyCloudy: "আংশিক মেঘলা",
      weatherCondition_Fog: "কুয়াশা",
      weatherCondition_Drizzle: "গুঁড়ি গুঁড়ি বৃষ্টি",
      weatherCondition_Rain: "বৃষ্টি",
      weatherCondition_Snow: "তুষার",
      weatherCondition_Thunderstorm: "বজ্রপাত",
      weatherLoading: "আবহাওয়া লোড হচ্ছে...",
      weatherError_locationPermission: "অবস্থানের অনুমতি প্রত্যাখ্যান করা হয়েছে। লাইভ আবহাওয়া দেখতে দয়া করে এটি সক্ষম করুন।",
      weatherError_locationGeneral: "আপনার অবস্থান পেতে முடியவில்லை। আবহাওয়া अनुपलब्ध।",
      weatherError_api: "আবহাওয়ার ডেটা আনা যায়নি। অনুগ্রহ করে পরে আবার চেষ্টা করুন।",
      feedbackView: 'মতামত',
      averageRating: 'গড় রেটিং',
      outOfFive: '5 এর মধ্যে',
      ratingDistribution: 'রেটিং বিতরণ',
      feedbackComments: 'মতামত মন্তব্য',
      noFeedbackYetTitle: 'এখনও কোন মতামত নেই',
      noFeedbackYetMessage: 'উপস্থিত ব্যক্তিরা মতামত জমা দেওয়ার পরে, তাদের রেটিং এবং মন্তব্যগুলি এখানে উপস্থিত হবে।',
    },
    mr: {
      ...baseTranslations,
      appName: 'मेलाव्हाइब',
      attendee: 'उपस्थित',
      organizer: 'आयोजक',
      logoutButton: 'लॉग आउट',
      reportViaSms: 'आपत्कालीन? एसएमएसद्वारे तक्रार करा',
      smsInstructions: 'तातडीच्या समस्यांसाठी, आमच्या सुरक्षा लाइनवर एक मजकूर पाठवा.',
      copyNumber: 'नंबर कॉपी करा',
      numberCopied: 'नंबर कॉपी झाला!',
      myReports: 'माझे अहवाल',
      reportIssue: 'समस्येची तक्रार करा',
      lostAndFound: 'हरवले आणि सापडले',
      description: 'वर्णन',
      addPhoto: 'फोटो जोडा',
      captureLocation: 'स्थान कॅप्चर करा',
      locationCaptured: 'स्थान कॅप्चर झाले!',
      photoPreview: 'फोटो पूर्वावलोकन',
      recordVoice: 'व्हॉइस नोट रेकॉर्ड करा',
      startRecording: 'रेकॉर्डिंग सुरू करा',
      stopRecording: 'रेकॉर्डिंग थांबवा',
      recording: 'रेकॉर्डिंग होत आहे...',
      micPermissionDenied: 'मायक्रोफोन परवानगी नाकारली. कृपया आपल्या ब्राउझर सेटिंग्जमध्ये ती सक्षम करा.',
      playRecording: 'तुमची व्हॉइस नोट',
      anonymousReport: 'हा अहवाल अनामिकपणे सबमिट करा',
      anonymousReportNote: 'अनामिक अहवाल नंतर "माझे अहवाल" मध्ये पाहिले जाऊ शकत नाहीत.',
      reviewReport: 'अहवाल पुनरावलोकन करा',
      reportPreviewTitle: 'आपल्या अहवालाचे पुनरावलोकन करा',
      yourPhoto: 'तुमचा फोटो',
      yourDescription: 'तुमचे वर्णन',
      yourVoiceNote: 'तुमची व्हॉइस नोट',
      capturedLocation: 'स्थान संलग्न केले आहे',
      aiAssessment: 'एआय ट्रायएज',
      aiPriority: 'एआय प्राधान्य',
      aiSuggestedTeam: 'सुचवलेली टीम',
      aiSummary: 'सारांश',
      goBackEdit: 'परत जा आणि संपादित करा',
      confirmSubmit: 'पुष्टी करा आणि सबमिट करा',
      reportSuccess: 'अहवाल यशस्वीरित्या सबमिट झाला!',
      issue_MedicalEmergency: 'वैद्यकीय आणीबाणी',
      issue_SafetyConcern: 'सुरक्षा चिंता',
      issue_Harassment: 'छळ',
      issue_TheftProperty: 'चोरी / मालमत्ता',
      issue_LostPerson: 'हरवलेली व्यक्ती',
      issue_SanitationIssue: 'स्वच्छता',
      issue_FacilityMaintenance: 'सुविधा',
      issue_FireHazard: 'आगीचा धोका',
      issue_InfoQuestion: 'माहिती',
      issue_Other: 'इतर',
      team_Medical: 'वैद्यकीय',
      team_Security: 'सुरक्षा',
      team_Sanitation: 'स्वच्छता',
      team_Facilities: 'सुविधा',
      team_General: 'सामान्य',
      priority_Low: 'कमी',
      priority_Medium: 'मध्यम',
      priority_High: 'उच्च',
      status_NEW: 'नवीन',
      status_IN_PROGRESS: 'प्रगतीपथावर',
      status_RESOLVED: 'निवारण झाले',
      dashboard: 'आयोजक डॅशबोर्ड',
      totalReports: 'एकूण अहवाल',
      sortBy: 'यानुसार लावा',
      sort_timestamp: 'सर्वात नवीन',
      sort_priority: 'सर्वोच्च प्राधान्य',
      gridView: 'ग्रिड',
      mapView: 'नकाशा',
      reportsView: 'अहवाल',
      crowdDensityView: 'गर्दीची घनता',
      viewOnMap: 'नकाशावर पहा',
      copyCoordinates: 'निर्देशांक कॉपी करा',
      coordinatesCopied: 'कॉपी झाले!',
      addComment: 'टीप',
      emptyDashboardTitle: 'सर्व काही स्पष्ट आहे!',
      emptyDashboardMessage: 'सध्या कोणतेही अहवाल नाहीत. सर्व काही सुरळीत चालू आहे असे दिसते.',
      emptyFilterTitle: 'कोणतेही अहवाल आढळले नाहीत',
      emptyFilterMessage: 'तुमच्या वर्तमान फिल्टर सेटिंग्जशी जुळणारे कोणतेही अहवाल नाहीत. दुसरी स्थिती निवडण्याचा प्रयत्न करा.',
      qrTools: 'QR साधने',
      logSmsReport: 'एसएमएस अहवाल लॉग करा',
      sendBroadcast: 'प्रक्षेपण',
      exportCSV: 'CSV निर्यात करा',
      analytics: 'विश्लेषण',
      myReportsTitle: 'माझे सबमिट केलेले अहवाल',
      noMyReports: 'तुम्ही कोणताही गैर-अनामिक अहवाल सबमिट केलेला नाही.',
      organizerNotes: "आयोजकांच्या नोट्स",
      confirmStatusChangeTitle: 'स्थिती बदलाची पुष्टी करा',
      confirmStatusChangeMessage: 'तुम्ही खात्रीने या अहवालाची स्थिती "{status}" मध्ये बदलू इच्छिता?',
      confirmStatusChangeButton: 'होय, स्थिती बदला',
      organizerNote: 'आयोजक टीप जोडा',
      addNotePlaceholder: 'इतर आयोजकांसाठी एक टिप्पणी जोडा...',
      submitNote: 'टीप सबमिट करा',
      lostAndFoundHub: "हरवले आणि सापडले केंद्र",
      viewFoundItems: "सापडलेल्या वस्तू",
      viewLostItems: "हरवलेल्या वस्तू",
      iFoundSomething: "मला काहीतरी सापडले",
      iLostSomething: "मी काहीतरी हरवले",
      noLfItems: "अद्याप कोणतीही वस्तू सूचीबद्ध नाही.",
      lfStatus_FOUND: "सापडले",
      lfStatus_LOST: "हरवले",
      itemCategory: "वस्तू श्रेणी",
      selectCategory: "एक श्रेणी निवडा...",
      category_Phone: "फोन",
      category_Wallet: "पाकीट / कार्ड्स",
      category_Keys: "चाव्या",
      category_Bag: "बॅग / बॅकपॅक",
      category_Clothing: "कपडे",
      category_Other: "इतर",
      itemDescription: "वर्णन",
      addAPhoto: "एक फोटो जोडा",
      submitItem: "वस्तू सबमिट करा",
      unresolvedItems: "न सुटलेले",
      resolvedItems: "सुटलेले",
      markAsResolved: "दावा केला/निकाली काढला म्हणून चिन्हांकित करा",
      itemClaimed: "वस्तूवर दावा केला/निकाली काढली",
      lfOrganizerView: "हरवले आणि सापडले",
      incidentReports: "घटना",
      analyticsReport: "कार्यक्रम विश्लेषण अहवाल",
      avgResolutionTime: "सरासरी निराकरण वेळ",
      minutes: "मिनिटे",
      notApplicable: "लागू नाही",
      reportsByType: "प्रकारानुसार अहवाल",
      reportsByPriority: "प्राधान्यानुसार अहवाल",
      noReportsForAnalytics: "विश्लेषण तयार करण्यासाठी पुरेसा डेटा नाही.",
      printReport: "अहवाल छापा",
      noLocationDataForMap: "नकाशावर प्रदर्शित करण्यासाठी स्थान डेटा असलेले कोणतेही अहवाल नाहीत.",
      viewReport: "संपूर्ण अहवाल पहा",
      densityLow: "कमी",
      densityMedium: "मध्यम",
      densityHigh: "उच्च",
      configSetupTitle: "अनुप्रयोग सेटअप आवश्यक आहे",
      configSetupPasteInstructions: "सुरुवात करण्यासाठी, खाली तुमचा फायरबेस कॉन्फिगरेशन ऑब्जेक्ट पेस्ट करा. हे तुमच्या फायरबेस प्रकल्प सेटिंग्जमध्ये प्रदान केले आहे.",
      configSetupPasteLabel: "फायरबेस कॉन्फिग ऑब्जेक्ट",
      configSetupSaveButton: "जतन करा आणि सुरू करा",
      configSetupOr: "किंवा",
      configSetupScanButton: "कन्सोलमधून QR कोड स्कॅन करा",
      configSetupScanInstructions: "अ‍ॅप स्वयंचलितपणे कॉन्फिगर करण्यासाठी इव्हेंट कन्सोलमध्ये प्रदर्शित केलेला QR कोड स्कॅन करा.",
      configSetupFooter: "हे कॉन्फिगरेशन तुमच्या डिव्हाइसवर स्थानिकरित्या संग्रहित केले आहे आणि अ‍ॅपला इव्हेंट डेटाबेसशी कनेक्ट करण्यासाठी आवश्यक आहे.",
      configEmptyError: "कॉन्फिगरेशन रिक्त असू शकत नाही.",
      configParsingError: "कॉन्फिगरेशन पार्स करू शकलो नाही. कृपया संपूर्ण जावास्क्रिप्ट ऑब्जेक्ट पेस्ट करा.",
      configSaveError: "कॉन्फिगरेशन जतन करू शकलो नाही. कृपया स्थानिक स्टोरेज सक्षम असल्याची खात्री करा.",
      invalidQRCode: "QR कोड वैध कॉन्फिगरेशन नाही.",
      scanError: "स्कॅन करताना एक त्रुटी आली.",
      cameraPermissionError: "QR कोड स्कॅन करण्यासाठी कॅमेरा परवानगी आवश्यक आहे.",
      organizerLoginTitle: "आयोजक लॉगिन",
      passwordLabel: "पासवर्ड",
      passwordPlaceholder: "पासवर्ड प्रविष्ट करा",
      signInButton: "साइन इन करा",
      incorrectPasswordError: "चुकीचा पासवर्ड. कृपया पुन्हा प्रयत्न करा.",
      qrToolsTitle: "QR कोड साधने",
      tabShareApp: "अ‍ॅप सामायिक करा",
      tabSyncReports: "अहवाल सिंक करा",
      tabShareSetup: "सेटअप सामायिक करा",
      shareAppInstructions: "उपस्थित लोक हा QR कोड स्कॅन करून त्यांच्या स्वतःच्या डिव्हाइसवर रिपोर्टिंग अ‍ॅप उघडू शकतात.",
      syncReportsTitle: "डिव्हाइसेस दरम्यान अहवाल सिंक करा",
      syncReportsShareInstructions: "या डिव्हाइसवरून दुसर्‍या डिव्हाइसवर अहवाल पाठविण्यासाठी, तुम्हाला सामायिक करायचे असलेले अहवाल निवडा आणि एक QR कोड तयार करा.",
      startSelection: "सामायिक करण्यासाठी अहवाल निवडा",
      syncReportsReceiveInstructions: "दुसर्‍या डिव्हाइसवरून अहवाल प्राप्त करण्यासाठी, त्यांनी तयार केलेला QR कोड स्कॅन करा.",
      receiveReports: "अहवाल प्राप्त करण्यासाठी स्कॅन करा",
      shareSetupTitle: "सेटअप कॉन्फिगरेशन सामायिक करा",
      shareSetupInstructions: "दुसरा आयोजक त्यांचे डिव्हाइस द्रुतपणे सेट करण्यासाठी हे स्कॅन करू शकतो. यात संवेदनशील कॉन्फिगरेशन डेटा आहे.",
      configQrWarning: "चेतावणी: या QR कोडमध्ये संवेदनशील कॉन्फिगरेशन क्रेडेन्शियल्स आहेत. ते सार्वजनिकपणे सामायिक करू नका.",
      shareQrDisplayTitle: "{count} अहवाल सामायिक करा",
      shareQrDisplayInstructions: "हे अहवाल त्यांच्या डिव्हाइसवर आयात करण्यासाठी दुसर्‍या आयोजकाला 'सिंक अहवाल' साधन वापरून हा QR कोड स्कॅन करण्यास सांगा.",
      shareQrDisplayNote: "या QR कोडमध्ये अहवाल डेटा आहे. जोपर्यंत हे मॉडेल उघडे आहे तोपर्यंत ते वैध असेल.",
      scanSuccess: "स्कॅन यशस्वी!",
      reportsImported: "नवीन अहवाल आयात केले",
      logSmsModalTitle: "एसएमएस अहवाल लॉग करा",
      logSmsModalInstructions: "डॅशबोर्डवर जोडण्यासाठी एसएमएस संदेशाद्वारे प्राप्त झालेला अहवाल व्यक्तिचलितपणे प्रविष्ट करा.",
      fullMessageContent: "पूर्ण संदेश सामग्री",
      createReport: "अहवाल तयार करा",
      broadcastModalTitle: "प्रक्षेपण घोषणा पाठवा",
      broadcastModalInstructions: "हा संदेश सर्व उपस्थितांसाठी अ‍ॅपच्या शीर्षस्थानी बॅनर म्हणून दिसेल.",
      broadcastMessage: "घोषणा संदेश",
      send: "पाठवा",
      cancel: "रद्द करा",
      cancelSelection: "निवड रद्द करा",
      generateShareQR: "{count} अहवालांसाठी QR तयार करा",
      weatherWidgetTitle: "थेट हवामान",
      weatherTemp: "{temp}°C",
      weatherFeelsLike: "{temp}°C सारखे वाटते",
      weatherCondition_Clear: "निरभ्र आकाश",
      weatherCondition_PartlyCloudy: "अंशतः ढगाळ",
      weatherCondition_Fog: "धुके",
      weatherCondition_Drizzle: "झिमझिम पाऊस",
      weatherCondition_Rain: "पाऊस",
      weatherCondition_Snow: "बर्फ",
      weatherCondition_Thunderstorm: "वादळ",
      weatherLoading: "हवामान लोड होत आहे...",
      weatherError_locationPermission: "स्थान प्रवेश नाकारला. थेट हवामान पाहण्यासाठी कृपया ते सक्षम करा.",
      weatherError_locationGeneral: "तुमचे स्थान मिळू शकले नाही. हवामान उपलब्ध नाही.",
      weatherError_api: "हवामान डेटा आणू शकलो नाही. कृपया नंतर पुन्हा प्रयत्न करा.",
      feedbackView: 'अभिप्राय',
      averageRating: 'सरासरी रेटिंग',
      outOfFive: '5 पैकी',
      ratingDistribution: 'रेटिंग वितरण',
      feedbackComments: 'अभिप्राय टिप्पण्या',
      noFeedbackYetTitle: 'अद्याप कोणताही अभिप्राय नाही',
      noFeedbackYetMessage: 'उपस्थितांनी अभिप्राय सबमिट केल्यावर, त्यांचे रेटिंग आणि टिप्पण्या येथे दिसतील.',
    },
    ta: {
      ...baseTranslations,
      appName: 'மெலாவைబ్',
      attendee: 'பங்கேற்பாளர்',
      organizer: 'அமைப்பாளர்',
      logoutButton: 'வெளியேறு',
      reportViaSms: 'அவசரமா? எஸ்எம்எஸ் மூலம் புகாரளிக்கவும்',
      smsInstructions: 'அவசர சிக்கல்களுக்கு, எங்கள் பாதுகாப்பு எண்ணிற்கு ஒரு குறுஞ்செய்தி அனுப்பவும்.',
      copyNumber: 'எண்ணை நகலெடு',
      numberCopied: 'எண் நகலெடுக்கப்பட்டது!',
      myReports: 'எனது அறிக்கைகள்',
      reportIssue: 'ஒரு சிக்கலைப் புகாரளி',
      lostAndFound: 'தவறியவை மற்றும் கண்டெடுக்கப்பட்டவை',
      description: 'விளக்கம்',
      addPhoto: 'புகைப்படம் சேர்',
      captureLocation: 'இருப்பிடத்தைப் பிடிக்கவும்',
      locationCaptured: 'இருப்பிடம் பிடிக்கப்பட்டது!',
      photoPreview: 'புகைப்பட முன்னோட்டம்',
      recordVoice: 'குரல் குறிப்பை பதிவு செய்',
      startRecording: 'பதிவைத் தொடங்கு',
      stopRecording: 'பதிவை நிறுத்து',
      recording: 'பதிவுசெய்கிறது...',
      micPermissionDenied: 'மைக்ரோஃபோன் அனுமதி மறுக்கப்பட்டது. உங்கள் உலாவி அமைப்புகளில் அதை இயக்கவும்.',
      playRecording: 'உங்கள் குரல் குறிப்பு',
      anonymousReport: 'இந்த அறிக்கையை அநாமதேயமாக சமர்ப்பிக்கவும்',
      anonymousReportNote: 'அநாமதேய அறிக்கைகளை பின்னர் "எனது அறிக்கைகள்" இல் பார்க்க முடியாது.',
      reviewReport: 'அறிக்கையை மதிப்பாய்வு செய்',
      reportPreviewTitle: 'உங்கள் அறிக்கையை மதிப்பாய்வு செய்யவும்',
      yourPhoto: 'உங்கள் புகைப்படம்',
      yourDescription: 'உங்கள் விளக்கம்',
      yourVoiceNote: 'உங்கள் குரல் குறிப்பு',
      capturedLocation: 'இடம் இணைக்கப்பட்டது',
      aiAssessment: 'AI வகைப்படுத்தல்',
      aiPriority: 'AI முன்னுரிமை',
      aiSuggestedTeam: 'பரிந்துரைக்கப்பட்ட குழு',
      aiSummary: 'சுருக்கம்',
      goBackEdit: 'திரும்பிச் சென்று திருத்து',
      confirmSubmit: 'உறுதிசெய்து சமர்ப்பிக்கவும்',
      reportSuccess: 'அறிக்கை வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது!',
      issue_MedicalEmergency: 'மருத்துவ அவசரம்',
      issue_SafetyConcern: 'பாதுகாப்பு கவலை',
      issue_Harassment: 'துன்புறுத்தல்',
      issue_TheftProperty: 'திருட்டு / சொத்து',
      issue_LostPerson: 'காணாமல் போனவர்',
      issue_SanitationIssue: 'சுகாதாரம்',
      issue_FacilityMaintenance: 'வசதிகள்',
      issue_FireHazard: 'தீ ஆபத்து',
      issue_InfoQuestion: 'தகவல்',
      issue_Other: 'மற்றவை',
      team_Medical: 'மருத்துவம்',
      team_Security: 'பாதுகாப்பு',
      team_Sanitation: 'சுகாதாரம்',
      team_Facilities: 'வசதிகள்',
      team_General: 'பொது',
      priority_Low: 'குறைந்த',
      priority_Medium: 'நடுத்தர',
      priority_High: 'உயர்',
      status_NEW: 'புதிய',
      status_IN_PROGRESS: 'செயல்பாட்டில் உள்ளது',
      status_RESOLVED: 'தீர்க்கப்பட்டது',
      dashboard: 'அமைப்பாளர் டாஷ்போர்டு',
      totalReports: 'மொத்த அறிக்கைகள்',
      sortBy: 'வரிசைப்படுத்து',
      sort_timestamp: 'சமீபத்தியவை',
      sort_priority: 'அதிக முன்னுரிமை',
      gridView: 'கட்டம்',
      mapView: 'வரைபடம்',
      reportsView: 'அறிக்கைகள்',
      crowdDensityView: 'கூட்ட நெரிசல்',
      viewOnMap: 'வரைபடத்தில் காண்க',
      copyCoordinates: 'ஆயத்தொலைவுகளை நகலெடு',
      coordinatesCopied: 'நகலெடுக்கப்பட்டது!',
      addComment: 'குறிப்பு',
      emptyDashboardTitle: 'அனைத்தும் தெளிவாக உள்ளது!',
      emptyDashboardMessage: 'தற்போது அறிக்கைகள் எதுவும் இல்லை. எல்லாம் சீராக இயங்குகிறது.',
      emptyFilterTitle: 'அறிக்கைகள் எதுவும் இல்லை',
      emptyFilterMessage: 'உங்கள் தற்போதைய வடிகட்டி அமைப்புகளுடன் எந்த அறிக்கையும் பொருந்தவில்லை. வேறு நிலையைத் தேர்ந்தெடுக்க முயற்சிக்கவும்.',
      qrTools: 'QR கருவிகள்',
      logSmsReport: 'எஸ்எம்எஸ் அறிக்கையை பதிவு செய்',
      sendBroadcast: 'ஒளிபரப்பு',
      exportCSV: 'CSV ஐ ஏற்றுமதி செய்',
      analytics: 'பகுப்பாய்வு',
      myReportsTitle: 'நான் சமர்ப்பித்த அறிக்கைகள்',
      noMyReports: 'நீங்கள் அநாமதேயமற்ற அறிக்கைகள் எதையும் சமர்ப்பிக்கவில்லை.',
      organizerNotes: "அமைப்பாளரின் குறிப்புகள்",
      confirmStatusChangeTitle: 'நிலை மாற்றத்தை உறுதிப்படுத்தவும்',
      confirmStatusChangeMessage: 'இந்த அறிக்கையின் நிலையை "{status}" என்று மாற்ற விரும்புகிறீர்களா?',
      confirmStatusChangeButton: 'ஆம், நிலையை மாற்று',
      organizerNote: 'அமைப்பாளர் குறிப்பைச் சேர்',
      addNotePlaceholder: 'மற்ற அமைப்பாளர்களுக்காக ஒரு கருத்தைச் சேர்க்கவும்...',
      submitNote: 'குறிப்பைச் சமர்ப்பிக்கவும்',
      lostAndFoundHub: "தவறியவை மற்றும் கண்டெடுக்கப்பட்டவை மையம்",
      viewFoundItems: "கண்டெடுக்கப்பட்ட பொருட்கள்",
      viewLostItems: "தவறிய பொருட்கள்",
      iFoundSomething: "நான் ஒன்றைக் கண்டுபிடித்தேன்",
      iLostSomething: "நான் ஒன்றை இழந்தேன்",
      noLfItems: "இன்னும் எந்தப் பொருளும் பட்டியலிடப்படவில்லை.",
      lfStatus_FOUND: "கண்டெடுக்கப்பட்டது",
      lfStatus_LOST: "தவறியது",
      itemCategory: "பொருள் வகை",
      selectCategory: "ஒரு வகையைத் தேர்ந்தெடுக்கவும்...",
      category_Phone: "தொலைபேசி",
      category_Wallet: "பணப்பை / அட்டைகள்",
      category_Keys: "சாவிகள்",
      category_Bag: "பை / முதுகுப்பை",
      category_Clothing: "ஆடை",
      category_Other: "மற்றவை",
      itemDescription: "விளக்கம்",
      addAPhoto: "ஒரு புகைப்படத்தைச் சேர்",
      submitItem: "பொருளைச் சமர்ப்பிக்கவும்",
      unresolvedItems: "தீர்க்கப்படாதவை",
      resolvedItems: "தீர்க்கப்பட்டவை",
      markAsResolved: "உரிமைகோரியது/தீர்க்கப்பட்டது எனக் குறிக்கவும்",
      itemClaimed: "பொருள் உரிமைகோரியது/தீர்க்கப்பட்டது",
      lfOrganizerView: "தவறியவை மற்றும் கண்டெடுக்கப்பட்டவை",
      incidentReports: "சம்பவங்கள்",
      analyticsReport: "நிகழ்வு பகுப்பாய்வு அறிக்கை",
      avgResolutionTime: "சராசரி தீர்வு நேரம்",
      minutes: "நிமிடங்கள்",
      notApplicable: "பொருந்தாது",
      reportsByType: "வகை வாரியாக அறிக்கைகள்",
      reportsByPriority: "முன்னுரிமை வாரியாக அறிக்கைகள்",
      noReportsForAnalytics: "பகுப்பாய்வுகளை உருவாக்க போதுமான தரவு இல்லை.",
      printReport: "அறிக்கையை அச்சிடுக",
      noLocationDataForMap: "வரைபடத்தில் காட்ட இருப்பிடத் தரவுடன் அறிக்கைகள் இல்லை.",
      viewReport: "முழு அறிக்கையைப் பார்க்கவும்",
      densityLow: "குறைவு",
      densityMedium: "நடுத்தரம்",
      densityHigh: "அதிகம்",
      configSetupTitle: "பயன்பாட்டு அமைப்பு தேவை",
      configSetupPasteInstructions: "தொடங்குவதற்கு, உங்கள் Firebase உள்ளமைவுப் பொருளைக் கீழே ஒட்டவும். இது உங்கள் Firebase திட்ட அமைப்புகளில் வழங்கப்பட்டுள்ளது.",
      configSetupPasteLabel: "Firebase உள்ளமைவு பொருள்",
      configSetupSaveButton: "சேமித்து துவக்கவும்",
      configSetupOr: "அல்லது",
      configSetupScanButton: "கன்சோலில் இருந்து QR குறியீட்டை ஸ்கேன் செய்யவும்",
      configSetupScanInstructions: "பயன்பாட்டை தானாக உள்ளமைக்க நிகழ்வு கன்சோலில் காட்டப்படும் QR குறியீட்டை ஸ்கேன் செய்யவும்.",
      configSetupFooter: "இந்த உள்ளமைவு உங்கள் சாதனத்தில் உள்ளூரில் சேமிக்கப்பட்டுள்ளது மற்றும் நிகழ்வு தரவுத்தளத்துடன் பயன்பாடு இணைக்கத் தேவைப்படுகிறது.",
      configEmptyError: "உள்ளமைவு காலியாக இருக்க முடியாது.",
      configParsingError: "உள்ளமைவைப் பாகுபடுத்த முடியவில்லை. முழுமையான ஜாவாஸ்கிரிப்ட் பொருளை ஒட்டவும்.",
      configSaveError: "உள்ளமைவைச் சேமிக்க முடியவில்லை. உள்ளூர் சேமிப்பகம் இயக்கப்பட்டிருப்பதை உறுதிசெய்யவும்.",
      invalidQRCode: "QR குறியீடு சரியான உள்ளமைவு அல்ல.",
      scanError: "ஸ்கேன் செய்யும் போது ஒரு பிழை ஏற்பட்டது.",
      cameraPermissionError: "QR குறியீடுகளை ஸ்கேன் செய்ய கேமரா அனுமதி தேவை.",
      organizerLoginTitle: "அமைப்பாளர் உள்நுழைவு",
      passwordLabel: "கடவுச்சொல்",
      passwordPlaceholder: "கடவுச்சொல்லை உள்ளிடவும்",
      signInButton: "உள்நுழைக",
      incorrectPasswordError: "தவறான கடவுச்சொல். மீண்டும் முயலவும்.",
      qrToolsTitle: "QR குறியீடு கருவிகள்",
      tabShareApp: "பயன்பாட்டைப் பகிரவும்",
      tabSyncReports: "அறிக்கைகளை ஒத்திசை",
      tabShareSetup: "அமைப்பைப் பகிரவும்",
      shareAppInstructions: "பங்கேற்பாளர்கள் இந்த QR குறியீட்டை ஸ்கேன் செய்து தங்கள் சொந்த சாதனங்களில் புகாரளிக்கும் பயன்பாட்டைத் திறக்கலாம்.",
      syncReportsTitle: "சாதனங்களுக்கு இடையில் அறிக்கைகளை ஒத்திசைக்கவும்",
      syncReportsShareInstructions: "இந்தச் சாதனத்திலிருந்து மற்றொரு சாதனத்திற்கு அறிக்கைகளை அனுப்ப, நீங்கள் பகிர விரும்பும் அறிக்கைகளைத் தேர்ந்தெடுத்து ஒரு QR குறியீட்டை உருவாக்கவும்.",
      startSelection: "பகிர அறிக்கைகளைத் தேர்ந்தெடுக்கவும்",
      syncReportsReceiveInstructions: "மற்றொரு சாதனத்திலிருந்து அறிக்கைகளைப் பெற, அவர்கள் உருவாக்கிய QR குறியீட்டை ஸ்கேன் செய்யவும்.",
      receiveReports: "அறிக்கைகளைப் பெற ஸ்கேன் செய்யவும்",
      shareSetupTitle: "அமைப்பு உள்ளமைவைப் பகிரவும்",
      shareSetupInstructions: "மற்றொரு அமைப்பாளர் தங்கள் சாதனத்தை விரைவாக அமைக்க இதை ஸ்கேன் செய்யலாம். இதில் முக்கியமான உள்ளமைவுத் தரவு உள்ளது.",
      configQrWarning: "எச்சரிக்கை: இந்த QR குறியீட்டில் முக்கியமான உள்ளமைவுச் சான்றுகள் உள்ளன. இதை பொதுவில் பகிர வேண்டாம்.",
      shareQrDisplayTitle: "{count} அறிக்கை(களை)ப் பகிரவும்",
      shareQrDisplayInstructions: "இந்த அறிக்கைகளை தங்கள் சாதனத்தில் இறக்குமதி செய்ய, 'அறிக்கைகளை ஒத்திசை' கருவியைப் பயன்படுத்தி இந்த QR குறியீட்டை ஸ்கேன் செய்யுமாறு மற்றொரு அமைப்பாளரிடம் கேளுங்கள்.",
      shareQrDisplayNote: "இந்த QR குறியீட்டில் அறிக்கை தரவு உள்ளது. இந்த உரையாடல் திறந்திருக்கும் வரை இது செல்லுபடியாகும்.",
      scanSuccess: "ஸ்கேன் வெற்றி!",
      reportsImported: "புதிய அறிக்கைகள் இறக்குமதி செய்யப்பட்டன",
      logSmsModalTitle: "எஸ்எம்எஸ் அறிக்கையைப் பதிவு செய்",
      logSmsModalInstructions: "டாஷ்போர்டில் சேர்க்க, எஸ்எம்எஸ் செய்தி மூலம் பெறப்பட்ட அறிக்கையை கைமுறையாக உள்ளிடவும்.",
      fullMessageContent: "முழு செய்தி உள்ளடக்கம்",
      createReport: "அறிக்கையை உருவாக்கு",
      broadcastModalTitle: "ஒளிபரப்பு அறிவிப்பை அனுப்பு",
      broadcastModalInstructions: "இந்தச் செய்தி அனைத்து பங்கேற்பாளர்களுக்கும் பயன்பாட்டின் மேலே ஒரு பேனராகத் தோன்றும்.",
      broadcastMessage: "அறிவிப்புச் செய்தி",
      send: "அனுப்பு",
      cancel: "ரத்துசெய்",
      cancelSelection: "தேர்வை ரத்துசெய்",
      generateShareQR: "{count} அறிக்கைகளுக்கான QR ஐ உருவாக்கு",
      weatherWidgetTitle: "நேரடி வானிலை",
      weatherTemp: "{temp}°C",
      weatherFeelsLike: "{temp}°C போல உணர்கிறது",
      weatherCondition_Clear: "தெளிவான வானம்",
      weatherCondition_PartlyCloudy: "பகுதி மேகமூட்டம்",
      weatherCondition_Fog: "மூடுபனி",
      weatherCondition_Drizzle: "தூறல்",
      weatherCondition_Rain: "மழை",
      weatherCondition_Snow: "பனி",
      weatherCondition_Thunderstorm: "இடியுடன் கூடிய மழை",
      weatherLoading: "வானிலை ஏற்றுகிறது...",
      weatherError_locationPermission: "இருப்பிட அணுகல் மறுக்கப்பட்டது. நேரடி வானிலையைப் பார்க்க அதை இயக்கவும்.",
      weatherError_locationGeneral: "உங்கள் இருப்பிடத்தைப் பெற முடியவில்லை. வானிலை கிடைக்கவில்லை.",
      weatherError_api: "வானிலை தரவைப் பெற முடியவில்லை. பின்னர் மீண்டும் முயற்சிக்கவும்.",
      feedbackView: 'கருத்து',
      averageRating: 'சராசரி மதிப்பீடு',
      outOfFive: '5க்கு',
      ratingDistribution: 'மதிப்பீடு விநியோகம்',
      feedbackComments: 'கருத்துகள்',
      noFeedbackYetTitle: 'இன்னும் கருத்து இல்லை',
      noFeedbackYetMessage: 'பங்கேற்பாளர்கள் கருத்தைச் சமர்ப்பித்தவுடன், அவர்களின் மதிப்பீடுகளும் கருத்துகளும் இங்கே தோன்றும்.',
    }
};